#!/bin/sh
set -eux

SAMU_DIR="$(pwd)"
# download cosmocc
cd /sc
wget https://github.com/jart/cosmopolitan/releases/download/3.3.3/cosmocc-3.3.3.zip
mkdir -p cosmocc
cd cosmocc
unzip ../cosmocc-3.3.3.zip

# register
cd /sc/cosmocc
sudo cp ./bin/ape-x86_64.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

# build fat binary
COSMO_DIR="/sc/cosmocc"
cd "$SAMU_DIR"
COSMOCC="/sc/cosmocc/bin/cosmocc"
make -j CC="$COSMOCC"
